export const coursesData = [
    { id: 1, courseCode: 'Course 1', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 2, courseCode: 'Course 2', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 3, courseCode: 'Course 3', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 4, courseCode: 'Course 4', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 5, courseCode: 'Course 5', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 6, courseCode: 'Course 6', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 7, courseCode: 'Course 7', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 8, courseCode: 'Course 8', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 9, courseCode: 'Course 9', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 10, courseCode: 'Course 10', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 11, courseCode: 'Course 11', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { id: 12, courseCode: 'Course 12', instructor: 'Prof.', semester: 'Spring 2023', description: 'Quote 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
];